syntax = "proto3";

package server;

service server_service {
  rpc init_greeting_request (greeting_request_message) returns (greeting_response_message);
  rpc cancel_greeting_request (greeting_request_message) returns (greeting_response_message);
}

// An enum for robot commands.
enum command {
  COMMAND_UNSPECIFIED = 0;
  MOVE_FORWARD = 1;
  MOVE_BACKWARD = 2;
  STOP = 3;
}

// This message represents a user's identity.
message identity {
  string id = 1;
  string name = 2;
  string language = 3;
}

// This message contains raw audio data.
message audio {
  int32 sample_rate = 1;
  int32 channels = 2;
  bytes data = 3;
}

// A request to initiate a greeting.
message greeting_request_message {
  string session_id = 1;
  identity person = 2;
}

// The response to a greeting request.
message greeting_response_message {
  string session_id = 1;
  bool success = 2;
  audio data = 3;
}

// A message sent during a chat session.
message chat_request_message {
  string session_id = 1;
  identity person = 2;
  audio data = 3;
}

// The response to a chat message, which may include a command.
message chat_response_message {
  string session_id = 1;
  bool success = 2;
  audio data = 3;
  command cmd = 4;
}