# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import robot_pb2 as robot__pb2


class robot_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.init_generic_request = channel.unary_unary(
                '/robot.robot_service/init_generic_request',
                request_serializer=robot__pb2.generic_message.SerializeToString,
                response_deserializer=robot__pb2.response_message.FromString,
                _registered_method=True)
        self.cancel_generic_request = channel.unary_unary(
                '/robot.robot_service/cancel_generic_request',
                request_serializer=robot__pb2.generic_message.SerializeToString,
                response_deserializer=robot__pb2.response_message.FromString,
                _registered_method=True)


class robot_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def init_generic_request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cancel_generic_request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_robot_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'init_generic_request': grpc.unary_unary_rpc_method_handler(
                    servicer.init_generic_request,
                    request_deserializer=robot__pb2.generic_message.FromString,
                    response_serializer=robot__pb2.response_message.SerializeToString,
            ),
            'cancel_generic_request': grpc.unary_unary_rpc_method_handler(
                    servicer.cancel_generic_request,
                    request_deserializer=robot__pb2.generic_message.FromString,
                    response_serializer=robot__pb2.response_message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.robot_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot.robot_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class robot_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def init_generic_request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.robot_service/init_generic_request',
            robot__pb2.generic_message.SerializeToString,
            robot__pb2.response_message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cancel_generic_request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.robot_service/cancel_generic_request',
            robot__pb2.generic_message.SerializeToString,
            robot__pb2.response_message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
