# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fr_pb2 as fr__pb2


class fr_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.init_fr_request = channel.unary_unary(
                '/fr.fr_service/init_fr_request',
                request_serializer=fr__pb2.fr_request_message.SerializeToString,
                response_deserializer=fr__pb2.fr_response_message.FromString,
                _registered_method=True)
        self.cancel_fr_request = channel.unary_unary(
                '/fr.fr_service/cancel_fr_request',
                request_serializer=fr__pb2.fr_request_message.SerializeToString,
                response_deserializer=fr__pb2.fr_response_message.FromString,
                _registered_method=True)


class fr_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def init_fr_request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cancel_fr_request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_fr_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'init_fr_request': grpc.unary_unary_rpc_method_handler(
                    servicer.init_fr_request,
                    request_deserializer=fr__pb2.fr_request_message.FromString,
                    response_serializer=fr__pb2.fr_response_message.SerializeToString,
            ),
            'cancel_fr_request': grpc.unary_unary_rpc_method_handler(
                    servicer.cancel_fr_request,
                    request_deserializer=fr__pb2.fr_request_message.FromString,
                    response_serializer=fr__pb2.fr_response_message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fr.fr_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fr.fr_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class fr_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def init_fr_request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fr.fr_service/init_fr_request',
            fr__pb2.fr_request_message.SerializeToString,
            fr__pb2.fr_response_message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cancel_fr_request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fr.fr_service/cancel_fr_request',
            fr__pb2.fr_request_message.SerializeToString,
            fr__pb2.fr_response_message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
