# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'robot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brobot.proto\x12\x05robot\"3\n\x0fgeneric_message\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x05\"7\n\x10response_message\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xa3\x01\n\rrobot_service\x12G\n\x14init_generic_request\x12\x16.robot.generic_message\x1a\x17.robot.response_message\x12I\n\x16\x63\x61ncel_generic_request\x12\x16.robot.generic_message\x1a\x17.robot.response_messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERIC_MESSAGE']._serialized_start=22
  _globals['_GENERIC_MESSAGE']._serialized_end=73
  _globals['_RESPONSE_MESSAGE']._serialized_start=75
  _globals['_RESPONSE_MESSAGE']._serialized_end=130
  _globals['_ROBOT_SERVICE']._serialized_start=133
  _globals['_ROBOT_SERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
