# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06server\"6\n\x08identity\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\"<\n\x05\x61udio\x12\x13\n\x0bsample_rate\x18\x01 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"P\n\x18greeting_request_message\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12 \n\x06person\x18\x02 \x01(\x0b\x32\x10.server.identity\"]\n\x19greeting_response_message\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x1b\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\r.server.audio\"i\n\x14\x63hat_request_message\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12 \n\x06person\x18\x02 \x01(\x0b\x32\x10.server.identity\x12\x1b\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\r.server.audio\"w\n\x15\x63hat_response_message\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x1b\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\r.server.audio\x12\x1c\n\x03\x63md\x18\x04 \x01(\x0e\x32\x0f.server.command*Q\n\x07\x63ommand\x12\x17\n\x13\x43OMMAND_UNSPECIFIED\x10\x00\x12\x10\n\x0cMOVE_FORWARD\x10\x01\x12\x11\n\rMOVE_BACKWARD\x10\x02\x12\x08\n\x04STOP\x10\x03\x32\xce\x01\n\x0eserver_service\x12\\\n\x15init_greeting_request\x12 .server.greeting_request_message\x1a!.server.greeting_response_message\x12^\n\x17\x63\x61ncel_greeting_request\x12 .server.greeting_request_message\x1a!.server.greeting_response_messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=547
  _globals['_COMMAND']._serialized_end=628
  _globals['_IDENTITY']._serialized_start=24
  _globals['_IDENTITY']._serialized_end=78
  _globals['_AUDIO']._serialized_start=80
  _globals['_AUDIO']._serialized_end=140
  _globals['_GREETING_REQUEST_MESSAGE']._serialized_start=142
  _globals['_GREETING_REQUEST_MESSAGE']._serialized_end=222
  _globals['_GREETING_RESPONSE_MESSAGE']._serialized_start=224
  _globals['_GREETING_RESPONSE_MESSAGE']._serialized_end=317
  _globals['_CHAT_REQUEST_MESSAGE']._serialized_start=319
  _globals['_CHAT_REQUEST_MESSAGE']._serialized_end=424
  _globals['_CHAT_RESPONSE_MESSAGE']._serialized_start=426
  _globals['_CHAT_RESPONSE_MESSAGE']._serialized_end=545
  _globals['_SERVER_SERVICE']._serialized_start=631
  _globals['_SERVER_SERVICE']._serialized_end=837
# @@protoc_insertion_point(module_scope)
