# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class server_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.init_greeting_request = channel.unary_unary(
                '/server.server_service/init_greeting_request',
                request_serializer=server__pb2.greeting_request_message.SerializeToString,
                response_deserializer=server__pb2.greeting_response_message.FromString,
                _registered_method=True)
        self.cancel_greeting_request = channel.unary_unary(
                '/server.server_service/cancel_greeting_request',
                request_serializer=server__pb2.greeting_request_message.SerializeToString,
                response_deserializer=server__pb2.greeting_response_message.FromString,
                _registered_method=True)


class server_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def init_greeting_request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cancel_greeting_request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_server_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'init_greeting_request': grpc.unary_unary_rpc_method_handler(
                    servicer.init_greeting_request,
                    request_deserializer=server__pb2.greeting_request_message.FromString,
                    response_serializer=server__pb2.greeting_response_message.SerializeToString,
            ),
            'cancel_greeting_request': grpc.unary_unary_rpc_method_handler(
                    servicer.cancel_greeting_request,
                    request_deserializer=server__pb2.greeting_request_message.FromString,
                    response_serializer=server__pb2.greeting_response_message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server.server_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('server.server_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class server_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def init_greeting_request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server.server_service/init_greeting_request',
            server__pb2.greeting_request_message.SerializeToString,
            server__pb2.greeting_response_message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cancel_greeting_request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server.server_service/cancel_greeting_request',
            server__pb2.greeting_request_message.SerializeToString,
            server__pb2.greeting_response_message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
